local opt = vim.opt
opt.wrap = true
opt.linebreak = true
opt.scrolloff = 4
opt.smartindent = true
opt.breakindent = true
opt.hlsearch = true
opt.incsearch = true
opt.inccommand = "split"
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.ignorecase = true
opt.smartcase = true
opt.title = true
opt.signcolumn = "yes"
opt.updatetime = 50
opt.titlestring = "%t%m"
opt.guicursor = ""
opt.swapfile = false
opt.backup = false
opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
opt.undofile = true
