set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',256col:Tc'
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q' 
set-environment -g COLORTERM "truecolor"
unbind C-b
set -g prefix `
bind-key ` last-window       
bind-key e send-prefix
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
bind x kill-pane # skip "kill-pane 1? (y/n)" promptprefix
unbind -T copy-mode-vi MouseDragEnd1Pane

setw -g mode-keys vi
set -g mouse on
set -sg escape-time 0
set -g base-index 1
set -g pane-base-index 1
set-option -g history-limit 50000

set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137                      
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-left-length 20
set -g status-right-length 50
set -g set-clipboard on  

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '
if "[[ $TERM =~ 256color]]" "
    set -g default-terminal 'tmux-256color';
    set -ga terminal-overrides ',tmux-256color:Tc' "
set -g default-terminal "screen-256color"
# Split horizontally in CWD with \
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

bind '"' split-window -v -c "#{pane_current_path}"

# New window with current path
bind c new-window -c "#{pane_current_path}"
# Resize panes with arrow keys
bind -r H resize-pane -L 1
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-l select-pane -L
bind -n M-h select-pane -R

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window
